### ISSUE TITLE
Create plug-in for Optimism mainnet

### ISSUE THREAD

**Issue by twhay** [openrelayxyz/din-caddy-plugins#1]
For supporting Optimism failover, I would like to have a new service enabled called Optimism mainnet. To start, it would support the following methods:

eth_blockNumber
eth_call
eth_chainId
eth_estimateGas
eth_gasPrice
eth_getBalance
eth_getBlockByHash
eth_getBlockByNumber
eth_getBlockTransactionCountByHash
eth_getBlockTransactionCountByNumber
eth_getCode
eth_getLogs
eth_getProof
eth_getStorageAt
eth_getTransactionByBlockHashAndIndex
eth_getTransactionByBlockNumberAndIndex
eth_getTransactionByHash
eth_getTransactionCount
eth_getTransactionReceipt
eth_getUncleByBlockHashAndIndex
eth_getUncleByBlockNumberAndIndex
eth_getUncleCountByBlockHash
eth_getUncleCountByBlockNumber
eth_sendRawTransaction
eth_subscribe
eth_unsubscribe
net_version
net_listening
net_peerCount
web3_clientVersion
web3_sha3

**Comment by AusIV** [comment]
Will need at least one endpoint to support this. Send that to me through private channels to protect keys.

**Comment by twhay** [comment]
I believe that now that Iris has provided you with that endpoint. I'll go ahead and close this issue.

**Comment by twhay** [comment]
Issue closed, endpoint has been created
